# Make rules for configuration files.
#
# $Id$

CFG		= kernel-$(VERSION)

CONFIGFILES	= \
	$(CFG)-x86_64.config

PLATFORMS	= x86_64
TEMPFILES	= $(addprefix temp-, $(addsuffix -generic, $(PLATFORMS)))

configs: $(CONFIGFILES)
	@rm -f kernel-*-config
	@rm -f $(TEMPFILES)
	@rm -f temp-generic temp-*-generic temp-*-generic-tmp

# Augment the clean target to clean up our own cruft
clean ::
	@rm -fv $(CONFIGFILES) $(TEMPFILES) temp-generic kernel-$(VERSION)*config

temp-x86-64: config-x86_64-generic /dev/null
	perl merge.pl $^  > $@

temp-x86_64-generic: temp-x86-64 /dev/null
	perl merge.pl $^  > $@

$(CFG)-x86_64.config: /dev/null temp-x86_64-generic
	perl merge.pl $^ x86_64 > $@
